# Generated by Django 5.2.8 on 2025-11-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vcmsg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vcmsg',
                'managed': False,
            },
        ),
    ]
