# Generated by Django 3.2.25 on 2024-05-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=45)),
                ('reply', models.CharField(max_length=45)),
                ('comp_id', models.IntegerField()),
            ],
            options={
                'db_table': 'feedback',
                'managed': False,
            },
        ),
    ]
