# Generated by Django 3.2.25 on 2024-05-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_details', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('work_status', models.CharField(max_length=45)),
                ('comp_id', models.IntegerField()),
                ('emp_id', models.IntegerField()),
            ],
            options={
                'db_table': 'work',
                'managed': False,
            },
        ),
    ]
