# Generated by Django 3.2.25 on 2024-05-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignWorkEmployee',
            fields=[
                ('assign_emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('work_status', models.CharField(max_length=45)),
                ('description', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'assign_work_employee',
                'managed': False,
            },
        ),
    ]
