# Generated by Django 3.2.25 on 2024-05-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeReg',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=45)),
                ('lastname', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField()),
                ('email', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('city', models.CharField(max_length=45)),
                ('district', models.CharField(max_length=45)),
                ('pincode', models.IntegerField()),
                ('phone_number', models.CharField(max_length=45)),
                ('marital_status', models.CharField(max_length=45)),
                ('join_date', models.DateField()),
                ('type', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'employee_reg',
                'managed': False,
            },
        ),
    ]
