"""
Django settings for crypqrshare project.

Generated by 'django-admin startproject' using Django 3.2.25.
"""

from pathlib import Path
import os
import mimetypes

# Build paths inside the project
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "gkpl+i+a8hz-ym1%@_&cz67m+cs50z5!24touua0vyys)okg1w")

DEBUG = False

ALLOWED_HOSTS = ["*"]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Your apps
    'assign_work_employee.apps.AssignWorkEmployeeConfig',
    'assign_work_manager.apps.AssignWorkManagerConfig',
    'feedback.apps.ComplaintConfig',
    'employee_reg.apps.EmployeeRegConfig',
    'login.apps.LoginConfig',
    'manager_reg.apps.ManagerRegConfig',
    'work.apps.WorkConfig',
    'temp.apps.TempConfig',
    'vcrypt.apps.VcryptConfig',
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',

    # Required for deployment on Render
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'crypqrshare.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],   # You can add template directories here if needed
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'crypqrshare.wsgi.application'


# -----------------------------
# DATABASE (LOCAL DEVELOPMENT)
# -----------------------------
# For Render deployment, we will replace this with env variables
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# -----------------------------
# STATIC & MEDIA CONFIGURATION
# -----------------------------

STATIC_URL = '/static/'

# Where Django collects static files for deployment
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Static files you created (CSS, JS, images)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

# Enable Whitenoise (required for Render)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (uploaded images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Fix CSS content-type issue
mimetypes.add_type("text/css", "css", True)


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
